import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export const exportToPDF = (title, messages, user) => {
  const doc = new jsPDF();
  const timestamp = new Date().toLocaleString();
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(40, 40, 40);
  doc.text("DocChat - Chat Export", 14, 22);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Title: ${title || "New Conversation"}`, 14, 30);
  doc.text(`User: ${user.name} (${user.email})`, 14, 35);
  doc.text(`Date: ${timestamp}`, 14, 40);
  
  // Table data
  const tableRows = messages.map((m, i) => [
    m.type === "user" ? "User" : "DocChat AI",
    m.text
  ]);

  autoTable(doc, {
    startY: 45,
    head: [["Sender", "Message"]],
    body: tableRows,
    theme: "striped",
    headStyles: { fillColor: [59, 130, 246], textColor: [255, 255, 255] },
    columnStyles: {
      0: { cellWidth: 30, fontStyle: "bold" },
      1: { cellWidth: "auto" }
    },
    styles: { overflow: "linebreak", cellPadding: 5 },
    margin: { top: 45 },
  });

  doc.save(`DocChat_${(title || "chat").replace(/\s+/g, "_")}_${Date.now()}.pdf`);
};

export const exportSummaryToPDF = (summary, title, user) => {
  const doc = new jsPDF();
  const timestamp = new Date().toLocaleString();

  // Header
  doc.setFontSize(22);
  doc.setTextColor(59, 130, 246);
  doc.text("AI Chat Summary Report", 14, 25);
  
  doc.setDrawColor(59, 130, 246);
  doc.setLineWidth(0.5);
  doc.line(14, 30, 196, 30);

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Original Chat: ${title || "New Conversation"}`, 14, 40);
  doc.text(`Generated for: ${user.name}`, 14, 45);
  doc.text(`Date: ${timestamp}`, 14, 50);

  // Content
  doc.setFontSize(12);
  doc.setTextColor(40, 40, 40);
  const splitText = doc.splitTextToSize(summary, 180);
  doc.text(splitText, 14, 65);

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${pageCount}`, 196, 285, { align: "right" });
    doc.text("Generated by DocChat AI", 14, 285);
  }

  doc.save(`DocChat_Summary_${Date.now()}.pdf`);
};

export const exportToMarkdown = (title, messages) => {
  let md = `# DocChat Export: ${title || "New Conversation"}\n\n`;
  md += `Generated on: ${new Date().toLocaleString()}\n\n---\n\n`;
  
  messages.forEach(m => {
    const role = m.type === "user" ? "**User**" : "**DocChat AI**";
    md += `### ${role}\n${m.text}\n\n---\n\n`;
  });

  const blob = new Blob([md], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `DocChat_${(title || "chat").replace(/\s+/g, "_")}_${Date.now()}.md`;
  a.click();
  URL.revokeObjectURL(url);
};

export const exportToText = (title, messages) => {
  let txt = `DocChat Export: ${title || "New Conversation"}\n`;
  txt += `Generated on: ${new Date().toLocaleString()}\n`;
  txt += `==========================================\n\n`;
  
  messages.forEach(m => {
    const role = m.type === "user" ? "USER" : "AI";
    txt += `[${role}]\n${m.text}\n\n`;
    txt += `------------------------------------------\n\n`;
  });

  const blob = new Blob([txt], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `DocChat_${(title || "chat").replace(/\s+/g, "_")}_${Date.now()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
};
